sudo: false
branches:
  only:
    - master
language: node_js
node_js:
  - "6"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
cache:
  directories:
    - node_modules
    - .yarn-cache
    - $HOME/.yarn-cache
before_install:
  - npm install -g yarn
install:
  - yarn install
before_script:
  - yarn add coveralls codeclimate-test-reporter
script:
  - yarn test
after_success:
  - yarn run coveralls
  - yarn run codeclimate
